version: "3.8"
services:
  database:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/data
    env_file:
      - .env

  webserver:
    build:
      context: ngnix
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      target: build
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env
    command: ["mvn", "spring-boot:run"]

volumes:
    db:
